### ISSUE TITLE
Participar do desenvolvimento em carnê

### ISSUE THREAD

**Issue by fazsites** [QuilhaSoft/JasperPHP-OpenBoleto#1]
Olá eu queria ajuda no projeto mas para geração de carnês sinceramente estou perdido no código para gerar o carnê, vi que não é a mesma forma do boleto.  vi que no arquivo xml do carnê coloca o query do mysql para fazer um loop. 
estou tendo o seguinte erro se tiver uma forma de me ajudar por favor: 
Fatal error: Uncaught exception 'JasperPHP\Exception' with message 'Não há transação ativa!!' in D:\www\1_sistemas\sistema_sapv\vendor\quilhasoft\jasperphp\src\Report.php on line 84

**Comment by Rctnet** [comment]
Oi @fazsites, mandei um update agora pouco para que rode o carnê sem conexão com o banco, mas pelo erro que você passou faltou descomentar a linha 165 de itauJasper.php.

**Comment by fazsites** [comment]
Obrigado meu caro!
