### ISSUE TITLE
Adicionar numParcelas na impressão do carne

### ISSUE THREAD

**Issue by marcoprodata** [QuilhaSoft/JasperPHP-OpenBoleto#10]
Mestre, como faço para adicionar o número da parcela na impressão do carnê? eu setei a mesma pela propriedade numParcelas, ai ela entra normalmente na linha digitavel e no código de barras, mas não consigo adiciona-la a impressão do carne em campo próprio.
Outro detalhe já falado, no caso do sicoob o barcode tem q ser interleaved 2 of 5, aqui mudei no meu e funcionou, mas no do repositório tá o code 128, assim alguns aplicativos de banco não conseguem ler.
Desde já agradeço a atenção recebida.

**Comment by Rctnet** [comment]
Boa tarde, eu sempre imprimi em modo carnê mesmo sem usar o campo de parcela, como eu uso o sistema mesmo sistema para emitir boletos para vários bancos e a maioria dele não da suporte para parcelas, decidi não implementar, sei que nos bancos que suportam tem controle de parcelas, tipo não da para pagar pular uma parcela, se quiser implementar é fácil, basta editar o aquivo jrxml com o jaspersoft studio, a edição é bem, e acrescentar o campo com nome igual ao que usar na entrada da biblioteca openboleto.

**Comment by marcoprodata** [comment]
> Boa tarde, eu sempre imprimi em modo carnê mesmo sem usar o campo de parcela, como eu uso o sistema mesmo sistema para emitir boletos para vários bancos e a maioria dele não da suporte para parcelas, decidi não implementar, sei que nos bancos que suportam tem controle de parcelas, tipo não da para pagar pular uma parcela, se quiser implementar é fácil, basta editar o aquivo jrxml com o jaspersoft studio, a edição é bem simples, e acrescentar o campo com nome igual ao que usar na entrada da biblioteca openboleto.

Tive que adicionar os seguintes códigos no Boleto.php:
logo após o $this->data = array_merge...
$this->data['num_parcelas'] = <variavelNumParcela>;

e tive que adicionar um getter
public function get_num_parcelas()
{
   return $this->data['num_parcelas'];
}


Parece que no objeto sicoob do openboleto ele não gera o num_parcelas no data do getoutput.

E adicionar o field no .jrxml, mas funcionou assim.
