### ISSUE TITLE
Problema nos campos demonstrativo e instruções

### ISSUE THREAD

**Issue by williandias360** [QuilhaSoft/JasperPHP-OpenBoleto#11]
Os campos demonstrativo e instruções só estão escrevendo "Array".
Como corrigir isso?
Obrigado

**Comment by Rctnet** [comment]
Ola, os dados devem ser interceptados por essa função
https://github.com/QuilhaSoft/JasperPHP-OpenBoleto/blob/778ecd22c546f7b22944dce46cf6e46afe666283/itauJasper.php#L134
para demonstrativo e logo abaixo tem a de instruções, veja se está usando os nomes dos campos corretamente, e se o seu código está passando por essas funcões

**Comment by williandias360** [comment]
Isso que eu não consegui entender.
Eu tenho que atribuir o retorno da função na posição demonstrativo do array?

**Comment by Rctnet** [comment]
Não, é automático, desde que use o mesmo nome de função sem o prefixo get_ .
A função '__get($prop)'
https://github.com/QuilhaSoft/JasperPHP-OpenBoleto/blob/778ecd22c546f7b22944dce46cf6e46afe666283/itauJasperA4.php#L52
que usa um método magico do PHP, intercepta a leitura da propriedade, verifica se existe algum método que contenha 'get_'+'nome do método' por exemplo, se existir executa ele, se não faz o retorno simples do conteúdo da variável, que está acontecendo no seu caso.

**Comment by williandias360** [comment]
Cara.. não consegui fazer funcionar esse método mágico não..kkkk
Mas resolvi chamando os métodos e atribuindo o valor deles na posição do array..kk

**Comment by Rctnet** [comment]
Sem problema, isso é igual matemática, não importa como vc fez, desde que esteja certo e vc entenda, rsrsr
