### ISSUE TITLE
Como pegar o conteúdo do pdf pra gravar em uma pasta especifica

### ISSUE THREAD

**Issue by marcoprodata** [QuilhaSoft/JasperPHP-OpenBoleto#15]
Mestres,

Como faço para ao invés de gerar a saida do pdf para o browser, pegar o conteúdo dele pra salvar numa pasta especifica.

**Comment by Rctnet** [comment]
Boa noite
Altere essa linha 

$pdf->Output('boleto.pdf',"I");  // metodo do TCPF para gerar saida para o browser

veja as opções disponíveis nessa pagina
http://www.fpdf.org/en/doc/output.htm

**Comment by marcoprodata** [comment]
Funcionou perfeito, obrigado
