### ISSUE TITLE
Código de barras do SICOOB não funciona para celulares

### ISSUE THREAD

**Issue by marcelocajaiba** [QuilhaSoft/JasperPHP-OpenBoleto#3]
Os celulares não conseguem lê o código de barras

**Comment by Rctnet** [comment]
Funciona sim, nos vários testes que fiz funcionou normalmente, tenho esse sistema em produção e nunca tive problema

**Comment by marcelocajaiba** [comment]
Olá RCnet o boleto da SICOOB  quando fui fazer leitura pelo celular não funcionou ai quando usei o que meu cliente gerou no site da SICOOB ele leu

**Comment by Rctnet** [comment]
Nesse caso pode ser que o openboleto esteja gerando o código de barras errado, o jasperPHP renderiza o numero que foi passado pelo openboleto, usando uma biblioteca própria para  geração de código de barras em pdf.

**Comment by marcelocajaiba** [comment]
mas o estranho que se eu usar o leitor de código de barras ele ler e consegue pagar

**Comment by Rctnet** [comment]
consegue postar o  arquivo pdf aqui para eu testar?

**Comment by marcelocajaiba** [comment]
Rogério tem como anexar aqui?

**Comment by Rctnet** [comment]
arraste o arquivo para a janela para anexar

**Comment by marcelocajaiba** [comment]
[boletoSICOOB.pdf](https://github.com/QuilhaSoft/JasperPHP-OpenBoleto/files/3086109/boletoSICOOB.pdf)

**Comment by marcelocajaiba** [comment]
obrigado por tentar ajudar

**Comment by marcelocajaiba** [comment]
se quiser envio o arquivo gerado no site da SICOOB para vc compara o código

**Comment by Rctnet** [comment]
usando o app barcode scaner carrega um código, com o app do banco itáu não carrega mesmo compare com o codigo gerado pelo sistema do banco, preferencialmente com os mesmos dados, data vencimento, emissor e valores

**Comment by marcelocajaiba** [comment]
ok obrigado vamos verificar

**Comment by marcelocajaiba** [comment]
a biblioteca JaspePHP parece está com problema, com código de barras dele da problema

**Comment by marcelocajaiba** [comment]
descobrimos que o barbecode do JaspePHP está code 128 parece que o correto é int2of5 mas quando coloca int2of5 não aparece. você sabe de algo Rogério?

**Comment by Rctnet** [comment]
já descobri, estou fazendo uns ajustes, logo posto um update

**Comment by Rctnet** [comment]
Fiz o update com a correção, o código de barras continua não lendo no app do itaú, mas pode ser pq eu não tenho configurado o meu sistema para o SICOOB, me avise se tiver sucesso, que a força esteja com você.

**Comment by Rctnet** [comment]
ha o update está no projeto QuilhaSoft/JasperPHP

**Comment by marcelocajaiba** [comment]
Olá Rogério obrigado pela atenção. tivemos que mudar para o boleto em html (fredroo) por que o jasperPHP  codifica errado o código de barras, em html todos os códigos de barras dos boletos funcionam. Ou seja não é erro do php.  mas vamos fazer o teste com o JaspePHP obrigado novamente

**Comment by ThayroneM** [comment]
Não estou conseguindo ler o codigo de barras dos boletos do bradesco pelo App, tentei modificar o tipo do BarCode do arquivo jrxml do Jasper para Int2of5 e começou a não aparecer mais o código de barras, eu sei que o problema é o tipo do BarCode, pq o padrão dos boletos que estou mexendo é int2of5, mas o tipo do BarCode no jrxml é Code128, pode me ajudar?

**Comment by Rctnet** [comment]
para modificar o tipo do código de barras pelo jasperStudio você deve excluir o objeto e criar denovo escolhendo in2of5
ou se quiser mecher no jrxmk direto modifique com esse código
<componentElement>
				<reportElement x="11" y="761" width="542" height="39" uuid="6a9b704c-ba5a-4d58-a882-f9727c554df0"/>
				<jr:barbecue xmlns:jr="http://jasperreports.sourceforge.net/jasperreports/components" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports/components http://jasperreports.sourceforge.net/xsd/components.xsd" type="Int2of5" drawText="false" checksumRequired="false">
					<jr:codeExpression><![CDATA[$F{numero_febraban}]]></jr:codeExpression>
				</jr:barbecue>
			</componentElement>

**Comment by Rctnet** [comment]
no meu ceslular leo o código de barras pelo app do itaú, mas como não era um boleto valido  deu erro de boleto não cadastrado na base, se der certo para você me avise, que eu vou criar um arquivo jrxml só para o SICOOB ..., ou faça um fork do propjeto e mande uma Pull Request com as alterações

**Comment by ThayroneM** [comment]
Muito obrigado resolveu !
