### ISSUE TITLE
Erro ao testar a plataforma.

### ISSUE THREAD

**Issue by MarkSamp** [QuilhaSoft/JasperPHP-OpenBoleto#4]
Prezados,

Fiz as instalações, que ocorreram sem erro. Ao utilizar o código de exemplo na principal do projeto, aparecem os seguintes erros:

Warning: simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '<' not found in /home/storage/3/b6/ad/antonionetoimovei1/public_html/include/vendor/quilhasoft/jasperphp/src/Report.php on line 42

Warning: simplexml_load_string(): bol01Files/boletoCarne.jrxml in /home/storage/3/b6/ad/antonionetoimovei1/public_html/include/vendor/quilhasoft/jasperphp/src/Report.php on line 42

Warning: simplexml_load_string(): ^ in /home/storage/3/b6/ad/antonionetoimovei1/public_html/include/vendor/quilhasoft/jasperphp/src/Report.php on line 42

Warning: Invalid argument supplied for foreach() in /home/storage/3/b6/ad/antonionetoimovei1/public_html/include/vendor/quilhasoft/jasperphp/src/Report.php on line 55

Warning: Invalid argument supplied for foreach() in /home/storage/3/b6/ad/antonionetoimovei1/public_html/include/vendor/quilhasoft/jasperphp/src/Report.php on line 58

Warning: Invalid argument supplied for foreach() in /home/storage/3/b6/ad/antonionetoimovei1/public_html/include/vendor/quilhasoft/jasperphp/src/Report.php on line 114

Warning: Invalid argument supplied for foreach() in /home/storage/3/b6/ad/antonionetoimovei1/public_html/include/vendor/quilhasoft/jasperphp/src/Report.php on line 133

Warning: Invalid argument supplied for foreach() in /home/storage/3/b6/ad/antonionetoimovei1/public_html/include/vendor/quilhasoft/jasperphp/src/Pdf.php on line 91
TCPDF ERROR: Some data has already been output, can't send PDF file

Lembrando que o código está exatamente igual ao exemplo aqui do projeto. A unica coisa que foi mudado é o require com o autoload do composer.

O que pode estar errado?

**Comment by MarkSamp** [comment]
Vi que o problema está na hora que o arquivo Reports.php quando achar o arquivo .jrxml dentro da pasta app.jrxml.

Ainda tentando arrumar o problema. :-(

**Comment by MarkSamp** [comment]
A única forma que eu encontrei foi de fixar essa variável no arquivo Reports.php:

public static $defaultFolder = '/home/storage/3/b6/ad/antonionetoimovei1/public_html/include/vendor/quilhasoft/jasperphp/app.jrxml';

Com o endereço fisico do servidor. Detalhe: getcwd não funcionou.

Existe alguma outra solução mais elegante?

**Comment by Rctnet** [comment]
Tem sim, como essa $defaultfolder é uma propriedade publica estática você pode alterar antes de instanciar.
No código do seu programa inclua
JasperPHP\Report::$defaultFolder = '/home/storage/3/b6/ad/antonionetoimovei1/public_html/include/vendor/quilhasoft/jasperphp/app.jrxml';
e deixe o código fonte da biblioteca livre de alterações
