### ISSUE TITLE
Erro na instalação da lib no composer.json

### ISSUE THREAD

**Issue by DiegoLisboaPires** [QuilhaSoft/JasperPHP-OpenBoleto#7]
Estou tentando executar a lib no meu projeto porém ela dar o seguinte erro ao executar composer
update no prompt de comando:
```
Problem 1
    - Installation request for quilhasoft/jasperphp-openboleto dev-master -> satisfiable by quilhasoft/jasperphp-openboleto[dev-master].
    - quilhasoft/jasperphp-openboleto dev-master requires quilhasoft/jasperphp dev-master -> satisfiable by quilhasoft/jasperphp[dev-master] but these conflict with your requirements or minimum-stability.
```
Se alguém tiver uma solução me ajude, de já agradeço :)

**Comment by Rctnet** [comment]
Boa tarde
ajustei o requerimento do jasperPHP-Openboleto estava com 7.0 e o jasperPHP estava com 5.3.0, coloquei todos par 5.3.0, agora deve instalar sem problemas
