### ISSUE TITLE
Erro tentando a impressão do carne

### ISSUE THREAD

**Issue by marcoprodata** [QuilhaSoft/JasperPHP-OpenBoleto#8]
Estou testando a biblioteca, e o tentar imprimir o carnê, tenho o seguinte erro:
simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found
na seguinte linha:
$report = new Report("bol01Files/boletoCarne.jrxml", array());

Estou testando em um projeto laravel sem conectar a um banco de dados, apenas criando os boletos manuais.

![image](https://user-images.githubusercontent.com/16479713/79045824-9bce4280-7be3-11ea-8081-4230bbc47135.png)

**Comment by Rctnet** [comment]
Ola @marcoprodata , se for igual no symfony, a pasta app.jrxml e pasta config (quando for conectar ao banco) devem estar dentro da pasta public

**Comment by Rctnet** [comment]
voce pode ainda definir antes de instanciar JasperPHP/Rerport::$defaultFolder  = "pasta raiz onde estão os arquivos jrxml"

**Comment by Rctnet** [comment]
Adicionei uma exceção na biblioteca para file not found.

**Comment by marcoprodata** [comment]
> JasperPHP/Rerport::$defaultFolder = "

Mestre, funcionou após copiar a pasta bol01Files pra pasta public, e trocar o JasperPHP\Pdf por PdfProcessor assim:
![image](https://user-images.githubusercontent.com/16479713/79046896-d20ec080-7be9-11ea-8560-b44e7003465a.png)

é isso mesmo?

**Comment by Rctnet** [comment]
sim

**Comment by Rctnet** [comment]
Já fiz a correção no git tb, obrigado pelo feedback
