### ISSUE TITLE
Mudar fonte no .jrxml

### ISSUE THREAD

**Issue by marcoprodata** [QuilhaSoft/JasperPHP-OpenBoleto#9]
Caros, tentei mudar a fonte no .jrxml e recebi o erro:
TCPDF ERROR: Could not include font definition file: arial narrow
Como posso alterar fontes na impressão do jrxml?

**Comment by Rctnet** [comment]
as fontes são as suportadas pela biblioteca tecnickcom/TCPDF
veja a lista em
https://github.com/tecnickcom/TCPDF/tree/master/fonts

**Comment by marcoprodata** [comment]
Obrigado mestre

**Comment by warquia** [comment]
Boa noite Marcos, poderia me ajudar a como configurar o JasperPHP-OpenBoleto ao meu projeto?

**Comment by elvysmarcos** [comment]
@warquia , como posso ajudar.

**Comment by warquia** [comment]
> @warquia , como posso ajudar.

Boa tarde, já conseguir resolver, muito obrigado pela disposição.
